#Thanks to https://raw.github.com/embarkmobile/android-maven-example/master/.travis.yml

branches:
  only:
    - master
    - release
    - fast-test

language: android
android:
  components:
    - android-10
    - sysimg-10
env:
  matrix:
    - ANDROID_TARGET=android-10   ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
    # Create and start emulator
    - android list targets
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

# We will run findbugs and checkstyle in the script phase
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dfindbugs.skip=true -Dcheckstyle.skip=true -Dpmd.skip=true -Dandroid.generateApk=false

before_script:
  - adb devices
  - ./wait_for_emulator

script: mvn install -Dandroid.device=test -Dmaven.javadoc.skip=true -Dandroid.dex.optimize=false

#play RS core tests only
#script: mvn install -pl robospice-core-parent/robospice-core-test -Dandroid.device=test -Dmaven.javadoc.skip=true -Dandroid.dex.optimize=false -Dandroid.test.classes=com.octo.android.robospice.SpiceManagerTest

after_failure:
  - adb logcat -d 
