#Thanks to https://raw.github.com/embarkmobile/android-maven-example/master/.travis.yml

branches:
  only:
    - master
    - release
    - fast-test

language: android
android:
  components:
    - android-8
    - sysimg-8
env:
  matrix:
    - ANDROID_TARGET=android-8   ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

# We will run findbugs and checkstyle in the script phase
install: mvn install -T 4 -DskipTests=true -Dmaven.javadoc.skip=true -Dfindbugs.skip=true -Dcheckstyle.skip=true -Dandroid.dex.optimize=false

before_script:
  - adb devices
  - ./wait_for_emulator

script: mvn install -T 4 -Dandroid.device=test -Dmaven.javadoc.skip=true -Dandroid.dex.optimize=false
